---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: permtest2
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: permtest2 
  name: permtest2
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi