apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: permtest2
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: permtest2 
  name: permtest2
spec:
  ports:
  - port: 8501
    protocol: TCP
    targetPort: 8501
  selector:
    app.kubernetes.io/instance: permtest2 
